name: Deploy to Railway

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install root deps
        run: npm ci

      - name: Build web
        run: npm run build

      - name: Install API deps
        run: |
          cd server
          npm ci
          npx prisma generate

      - name: Deploy to Railway
        uses: railwayapp/railway-action@v1
        with:
          project: ${{ secrets.RAILWAY_PROJECT_ID }}
          service: ${{ secrets.RAILWAY_SERVICE_ID }}
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
